---
name: exercise-3

on: 
   push:
       branches:
           - dev
jobs:
    exercise3:
        runs-on: ubuntu-latest
        steps:
            - name: ping test
              run: curl-I https://google.com
            - name: check the url exist
              run:  wget --spider https://google.com
            - name: test the ping command
              run: ping -c 4 google.com